from __future__ import annotations

import json
import pandas as pd
from common_v017 import jsonable, save_json, threshold_mapping

def save_tuning(p,r):
    a=p.args; prefix=f"v017_{p.num_exits}exit"
    r.all_df.sort_values(["quality_constraints_met","estimated_flops_saved_pct"],ascending=[False,False]).to_csv(p.out_dir/f"{prefix}_all_candidates.csv",index=False)
    r.pareto.sort_values("estimated_flops_saved_pct",ascending=False).to_csv(p.out_dir/f"{prefix}_pareto_front.csv",index=False)
    pd.DataFrame(r.history).to_csv(p.out_dir/f"{prefix}_optimization_history.csv",index=False)
    pd.DataFrame([{**{k:jsonable(v) for k,v in r.selected.items()},"selection_status":r.status,"deployment_eligible":r.eligible}]).to_csv(p.out_dir/f"{prefix}_selected_policy.csv",index=False)
    params=json.loads(str(r.selected["parameters_json"]))
    frozen={"schema_version":1,"experiment":"v0.17_EE_sequential_active_budget_anytime_exit","branch":"active_budget_anytime_exit_v0.4","architecture_name":f"{p.num_exits}-exit","run_dir":str(p.run_dir),"checkpoint":str(p.checkpoint),"validation_manifest":str(p.manifest),"validation_features_root":str(p.features),"labels_json":str(a.labels_json.resolve()),"lats_config_json":str(a.lats_config_json.resolve()),"labels":p.labels,"architecture":{"model":"ExitNet/TinyAudioCNN","tap_blocks":list(p.taps),"num_exits":p.num_exits,"n_mels":p.n_mels,"frames_observed":int(p.frames),"sequential_route":" -> ".join(f"Exit {i}" for i in range(1,p.num_exits+1))},"threshold_mode":a.threshold_mode,"thresholds_by_exit":{f"exit{i+1}":threshold_mapping(p.labels,t) for i,t in enumerate(p.thresholds)},"risk_design":{"definition":"Validation-only per-label correction frequency relative to the final exit.","weights_by_early_exit":p.risk.tolist(),"correction_counts_by_early_exit":p.risk_counts.tolist()},"optimisation":{"algorithm":"constraint-aware NSGA-II-style sequential search","population_size":int(a.population_size),"generations":int(a.generations),"seed":int(a.seed),"gene_block_per_early_exit":["mean_confidence_threshold","max_probability_delta","max_label_risk",*[f"margin_{label}" for label in p.labels]],"selection":"safety-buffered Pareto knee","safety_fraction":float(a.safety_fraction),"unique_candidates_evaluated":len(r.all_df),"pareto_candidates":len(r.pareto)},"selection_constraints":{"max_parent_macro_f1_drop":a.max_macro_f1_drop,"max_parent_micro_f1_drop":a.max_micro_f1_drop,"max_parent_exact_match_drop":a.max_exact_match_drop,"max_parent_hamming_increase":a.max_hamming_increase,"minimum_total_early_fraction":a.min_total_early_fraction,"minimum_exit1_fraction":a.min_exit1_fraction,"fold_upper_confidence_required":True},"reference_final_exit_validation":p.parent.reference_metrics,"selected_policy":{"selection_status":r.status,"deployment_eligible":r.eligible,"parameters":params,"validation_metrics":{k:jsonable(v) for k,v in r.selected.items() if k not in {"parameters_json","genes_json"}}},"estimated_flops_by_exit":{k:float(v) for k,v in p.flops.items()},"important_note":"Every non-final exit participates; holdout parameters remain frozen."}
    path=p.out_dir/f"frozen_sequential_policy_{p.num_exits}exit_v017.json"; save_json(frozen,path)
    cols=["estimated_flops_saved_pct","total_early_fraction","exit1_fraction","average_exit_depth","parent_macro_f1","parent_micro_f1","parent_exact_match","parent_hamming_loss","robust_macro_drop","robust_micro_drop","robust_exact_drop","robust_hamming_increase","quality_constraints_met"]
    print(f"\nV0.17 sequential {p.num_exits}-exit tuning complete"); print("-"*126); print(f"Validation segments: {len(p.y)}\nValidation parents: {len(p.parent.parent_ids)}\nUnique candidates tested: {len(r.all_df)}\nPareto candidates: {len(r.pareto)}\nSelection status: {r.status}\nDeployment eligible: {r.eligible}\nFrozen policy: {path}"); print(pd.DataFrame([r.selected])[cols].to_string(index=False))
