# models/anytime_exit_net.py

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import torch
import torch.nn as nn

from models.exit_net import ExitNet


@dataclass
class AnytimeExitState:
    """State carried between incremental exit evaluations.

    Attributes:
        feature_map:
            Backbone feature map produced by the most recently executed block.
        block_index:
            One-based index of the last backbone block already executed.
        next_exit_index:
            Zero-based index of the next exit to evaluate. After the final exit,
            this equals ``num_exits``.
        prev_hint:
            Optional hint generated by the most recently evaluated early exit.
        finished:
            True after the final exit has been evaluated.
    """

    feature_map: torch.Tensor
    block_index: int
    next_exit_index: int
    prev_hint: Optional[torch.Tensor] = None
    finished: bool = False

    @property
    def completed_exit_number(self) -> int:
        """Return the one-based exit number most recently evaluated."""
        return int(self.next_exit_index)


class AnytimeExitNet(nn.Module):
    """Incremental inference wrapper for an existing :class:`ExitNet`.

    The original ``ExitNet.forward`` remains unchanged for training and cached
    full-forward evaluation. This wrapper executes only the backbone blocks
    needed to reach the next exit, allowing a policy to stop before deeper
    blocks are computed.

    Typical three-exit flow for ``tap_blocks=(1, 3)``::

        logits1, state = model.start(x)          # runs block 1 only
        logits2, state = model.continue_from(state)  # runs blocks 2-3
        logits3, state = model.continue_from(state)  # runs blocks 4-5

    The wrapper adds no trainable parameters and does not change model weights.
    Load the checkpoint into the underlying ``ExitNet`` before wrapping it.
    """

    def __init__(self, exit_net: ExitNet):
        super().__init__()

        if not isinstance(exit_net, ExitNet):
            raise TypeError(
                "exit_net must be an instance of models.exit_net.ExitNet, "
                f"got {type(exit_net)}"
            )

        self.exit_net = exit_net
        self._validate_backbone_contract()

    @property
    def num_exits(self) -> int:
        return int(self.exit_net.num_exits)

    @property
    def tap_blocks(self) -> tuple[int, ...]:
        return tuple(int(v) for v in self.exit_net.backbone.tap_blocks)

    @property
    def final_block_index(self) -> int:
        return int(len(self.exit_net.backbone.blocks))

    def _validate_backbone_contract(self) -> None:
        backbone = self.exit_net.backbone

        required = ("blocks", "tap_blocks", "_tap_pool")
        missing = [name for name in required if not hasattr(backbone, name)]
        if missing:
            raise TypeError(
                "AnytimeExitNet requires a staged backbone exposing "
                f"{required}. Missing: {missing}"
            )

        tap_blocks = [int(v) for v in backbone.tap_blocks]
        if not tap_blocks:
            raise ValueError("The backbone must expose at least one tap block.")
        if tap_blocks != sorted(set(tap_blocks)):
            raise ValueError(
                "backbone.tap_blocks must be strictly increasing and unique, "
                f"got {tap_blocks}"
            )
        if len(tap_blocks) != len(self.exit_net.exit_heads):
            raise ValueError(
                f"Backbone exposes {len(tap_blocks)} tap blocks but ExitNet has "
                f"{len(self.exit_net.exit_heads)} early-exit heads."
            )

        final_block = int(len(backbone.blocks))
        if tap_blocks[-1] >= final_block:
            raise ValueError(
                "Early-exit tap blocks must occur before the final backbone "
                f"block. Got taps={tap_blocks}, final_block={final_block}."
            )

    def _run_blocks(
        self,
        feature_map: torch.Tensor,
        *,
        start_block: int,
        end_block: int,
    ) -> torch.Tensor:
        """Run a contiguous one-based backbone block range."""
        start_block = int(start_block)
        end_block = int(end_block)

        if start_block < 1:
            raise ValueError(f"start_block must be >= 1, got {start_block}")
        if end_block > self.final_block_index:
            raise ValueError(
                f"end_block={end_block} exceeds final block "
                f"{self.final_block_index}."
            )
        if start_block > end_block:
            return feature_map

        out = feature_map
        for block_no in range(start_block, end_block + 1):
            out = self.exit_net.backbone.blocks[block_no - 1](out)
        return out

    def _early_exit_logits(
        self,
        *,
        exit_index: int,
        feature_map: torch.Tensor,
        prev_hint: Optional[torch.Tensor],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor]]:
        """Evaluate one early-exit head and optionally create its hint."""
        exit_index = int(exit_index)
        tap = self.exit_net.backbone._tap_pool(feature_map)

        head_in = tap
        if self.exit_net.use_exit_hints and prev_hint is not None:
            head_in = torch.cat([head_in, prev_hint], dim=1)

        logits = self.exit_net.exit_heads[exit_index](head_in)
        next_hint = prev_hint

        if self.exit_net.use_exit_hints:
            next_hint = self.exit_net._make_hint(
                logits,
                self.exit_net.hint_projections[exit_index],
            )

        return logits, next_hint

    def start(self, x: torch.Tensor) -> tuple[torch.Tensor, AnytimeExitState]:
        """Run from the input through the first early exit only."""
        first_tap_block = int(self.tap_blocks[0])
        feature_map = self._run_blocks(
            x,
            start_block=1,
            end_block=first_tap_block,
        )
        logits, prev_hint = self._early_exit_logits(
            exit_index=0,
            feature_map=feature_map,
            prev_hint=None,
        )

        state = AnytimeExitState(
            feature_map=feature_map,
            block_index=first_tap_block,
            next_exit_index=1,
            prev_hint=prev_hint,
            finished=False,
        )
        return logits, state

    def continue_from(
        self,
        state: AnytimeExitState,
    ) -> tuple[torch.Tensor, AnytimeExitState]:
        """Continue from a prior state to the next exit.

        The method executes only the blocks between the previous exit and the
        next exit. Calling it after the final exit raises ``RuntimeError``.
        """
        if not isinstance(state, AnytimeExitState):
            raise TypeError(
                "state must be an AnytimeExitState, "
                f"got {type(state)}"
            )
        if state.finished:
            raise RuntimeError("Cannot continue: the final exit is complete.")

        next_exit_index = int(state.next_exit_index)

        # Another intermediate exit remains.
        if next_exit_index < len(self.exit_net.exit_heads):
            target_block = int(self.tap_blocks[next_exit_index])
            feature_map = self._run_blocks(
                state.feature_map,
                start_block=int(state.block_index) + 1,
                end_block=target_block,
            )
            logits, prev_hint = self._early_exit_logits(
                exit_index=next_exit_index,
                feature_map=feature_map,
                prev_hint=state.prev_hint,
            )

            next_state = AnytimeExitState(
                feature_map=feature_map,
                block_index=target_block,
                next_exit_index=next_exit_index + 1,
                prev_hint=prev_hint,
                finished=False,
            )
            return logits, next_state

        # No intermediate exit remains: execute only the remaining final blocks.
        feature_map = self._run_blocks(
            state.feature_map,
            start_block=int(state.block_index) + 1,
            end_block=self.final_block_index,
        )
        final_feat = feature_map.view(feature_map.size(0), -1)

        final_in = final_feat
        if self.exit_net.use_exit_hints and state.prev_hint is not None:
            final_in = torch.cat([final_in, state.prev_hint], dim=1)

        logits = self.exit_net.final_head(final_in)
        next_state = AnytimeExitState(
            feature_map=feature_map,
            block_index=self.final_block_index,
            next_exit_index=self.num_exits,
            prev_hint=state.prev_hint,
            finished=True,
        )
        return logits, next_state

    def forward_all_staged(self, x: torch.Tensor) -> list[torch.Tensor]:
        """Evaluate every exit incrementally for equivalence testing/auditing."""
        outputs: list[torch.Tensor] = []

        logits, state = self.start(x)
        outputs.append(logits)

        while not state.finished:
            logits, state = self.continue_from(state)
            outputs.append(logits)

        return outputs

    def forward(self, x: torch.Tensor) -> list[torch.Tensor]:
        """Return all exits through the staged path.

        Dynamic policies should call ``start`` and ``continue_from`` directly so
        they can stop before deeper blocks execute.
        """
        return self.forward_all_staged(x)
